### ISSUE TITLE
bs4Dash integration

### ISSUE THREAD

**Issue by analytichealth** [feddelegrand7/Rnightly#1]
Hi @feddelegrand7 this looks like an awesome package! Any plans to integrate with the bs4Dash package? As I'm sure you're aware bs4Dash is a really nice framework for Shiny apps.

Below I've used some basic example code from here: https://rinterface.github.io/bs4Dash/articles/bs4Intro.html

The Rnighlty functions have an effect but don't fully produce the desired effect:

```
# remotes::install_github("feddelegrand7/Rnightly")

library(shiny)
library(bs4Dash)

shiny::shinyApp(
  ui = bs4DashPage(
    title = "Basic Dashboard",
    navbar = bs4DashNavbar(),
    sidebar = bs4DashSidebar(
      status = "primary",
      title = "bs4Dash",
      brandColor = "primary",
      url = "https://www.google.fr",
      src = "https://adminlte.io/themes/AdminLTE/dist/img/user2-160x160.jpg",
      elevation = 3,
      opacity = 0.8,
      bs4SidebarUserPanel(
        img = "https://image.flaticon.com/icons/svg/1149/1149168.svg",
        text = "Welcome Onboard!"
      ),
      bs4SidebarMenu(
        bs4SidebarHeader("Header 1"),
        bs4SidebarMenuItem(
          "Item 1",
          tabName = "item1",
          icon = "sliders"
        )
      )
    ),
    body = bs4DashBody(
    # initialise the Rnightly package for the dark/light toggle
    Rnightly::use_nightly(),
      bs4TabItems(
        bs4TabItem(
          tabName = "item1",
	  actionButton(inputId = "Rnightly_btn", label = "Rnightly toggle"), 
          Rnightly::nightly(trigElement = "Rnightly_btn"),          
          fluidRow(
             bs4Card(
             title = "Box",
	     width = 6,
	     p("Box Content")
           )
          )
        )
      )
    )
  ),
  server = function(input, output) {}
)
``` 
Thank you

**Comment by feddelegrand7** [comment]
Hi @analytichealth, thank you for indicating me this issue. I'm not sure about the source of the problem but I think the nightly js library doesn't support currently advanced bootstrap frameworks as it's still in the TODO list. Further, it's possible that bs4Dash uses javascript dependencies that may conflict with nightly js.

**Comment by feddelegrand7** [comment]
Meanwhile you can use the  fresh package (https://github.com/dreamRs/fresh) to apply advanced themes to bs4Dash (Thank you @DivadNojnarg for the tip)

**Comment by analytichealth** [comment]
Thanks very much @feddelegrand7 I'll test out the fresh package and close this issue
